# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install azure-devops
    pip install numpy
    #pip install python-dateutil
    pip install -r requirements.txt
    pip install absl-py
    pip install tensorflow
    pip install pandas
    pip install tqdm
    #pip freeze > requirements.txt
    #pip install -r requirements.txt

- script: |
    #pip install pytest pytest-azurepipelines
    #pytest
    echo "Config File"
    echo $(CONFIGFILE)
    python ./src/runner.py $(CONFIGFILE)
  displayName: 'Run Python Script'

- script: |
    git config --global user.email "kannan.ramamoorthy@assurity.co.nz"
    git config --global user.name "Kannan Ramamoorthy"
    git config --global url."git@github.com:".insteadOf "https://github.com/"
    echo "export GIT_TERMINAL_PROMPT=1" >> ~/.bashrc || ~/.zshrc
    
    #cat ~/.gitconfig

    git add out/WorkItemExtract.json
    git commit -m "Latest Extract."  
    git push origin HEAD:master
    git show-ref
  displayName: 'Push Extract to Git'
