# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
- group: common-variable-group
- name: key.pat
  value: $[key.pat]

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install azure-devops
    pip install numpy
    #pip install python-dateutil
    pip install -r requirements.txt
    pip install absl-py
    pip install tensorflow
    pip install pandas
    pip install tqdm
  displayName: 'Install Dependencies'

- script: |
    cd ./src
    echo $(PAT)
    echo $(pat)

    python ./runner.py -passwd $(pat)
  displayName: 'Run Python Script'

